// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartFood.DAL.DataContext;

namespace SmartFood.DAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartFood.DAL.Entities.Box", b =>
                {
                    b.Property<int>("Id_box")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateEntry_box")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_delivery")
                        .HasColumnType("int");

                    b.Property<int>("Id_product")
                        .HasColumnType("int");

                    b.Property<decimal>("Initial_weight_product")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ShelfLife_box")
                        .HasColumnType("int");

                    b.HasKey("Id_box");

                    b.ToTable("Boxes");
                });

            modelBuilder.Entity("SmartFood.DAL.Entities.Delivery", b =>
                {
                    b.Property<int>("Id_delivery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime_delivery")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_foodEstablishment")
                        .HasColumnType("int");

                    b.Property<int>("Id_shipper")
                        .HasColumnType("int");

                    b.HasKey("Id_delivery");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("SmartFood.DAL.Entities.FoodEstablishment", b =>
                {
                    b.Property<int>("Id_foodEstablishment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address_foodEstablishment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login_foodEstablishment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile_foodEstablishment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_foodEstablishment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password_foodEstablishment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_foodEstablishment");

                    b.ToTable("FoodEstablishments");
                });

            modelBuilder.Entity("SmartFood.DAL.Entities.HistoryBox", b =>
                {
                    b.Property<int>("Id_history")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime_history")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Humidity_box")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Id_box")
                        .HasColumnType("int");

                    b.Property<decimal>("Temperature_box")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Weight_box")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_history");

                    b.ToTable("HistoryBoxes");
                });

            modelBuilder.Entity("SmartFood.DAL.Entities.Product", b =>
                {
                    b.Property<int>("Id_product")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Humidity_product")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Id_shipper")
                        .HasColumnType("int");

                    b.Property<string>("Name_product")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price_product")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Temperature_product")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Weight_product")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_product");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SmartFood.DAL.Entities.Shipper", b =>
                {
                    b.Property<int>("Id_shipper")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address_shipper")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login_shipper")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile_shipper")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_shipper")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password_shipper")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_shipper");

                    b.ToTable("Shippers");
                });
#pragma warning restore 612, 618
        }
    }
}
